experiment_name: fp_beta1
output_dir_base: <<INSERT PATH>>
hgnc_gene_names: <<INSERT PATH>>

dataloader_params:
  embedding_path: <<INSERT PATH>>
  genotype_path: <<INSERT PATH>>
  phenotype_dir: <<INSERT PATH>>
  use_prs: true
  normalize_covariates: true
  dataset_version: filteredv3
  test_split_size: 0.25
  val_split_size: 0.1
  split_seed: 0
  train_individuals_path: <<INSERT PATH>>
  covariates_path: <<INSERT PATH>>
  prs_path: <<INSERT PATH>>
  # gene_subset:
  #   - ENSG00000130164
  #   - ENSG00000169174

training_params:
  learning_rate: 0.001
  epochs: 25
  nonlinearity: softplus # choose from ['relu', 'silu', 'elu', 'gelu', 'softplus']
  follow_metric: r2
  weight_decay: 0
  batch_size: 16394
  early_stopping: False
  wandb_logging: True
  wandb_project_name: funcrvp_beta
  wandb_dir: <<INSERT PATH>>
  old_optuna_journal_log: <<INSERT PATH>>
  old_model_version: v108cov_deepRVAT
  old_model_embedding: omics_pops

hpopt_params:
  n_repeats: 1
  n_trials: 100
  objective_direction: maximize
  hpopt_file: /s/project/geno2pheno/hyperopt/optuna/new_journal.log

traits:
  # - Albumin
  - Alkaline_phosphatase
  # - Apolipoprotein_A
  # - Apolipoprotein_B
  # - BodyMassIndex
  # - Calcium
  # - Cholesterol
  # - Creatinine
  # - Cystatin_C
  # - Direct_bilirubin
  # - Erythrocyte_count
  # - Erythrocyte_distribution_width
  # - Gamma_glutamyltransferase
  # - Glucose
  # - HDL_cholesterol
  # - High_light_scatter_reticulocyte_count
  # - High_light_scatter_reticulocyte_percentage
  # - IGF1
  - LDL_direct
  # - Lymphocyte_percentage
  # - Mean_corpuscular_haemoglobin
  # - Mean_corpuscular_volume
  # - Mean_reticulocyte_volume
  # - Mean_sphered_cell_volume
  # - Neutrophill_count
  # - Phosphate
  # - Platelet_count
  # - Platelet_crit
  # - Platelet_distribution_width
  # - Reticulocyte_count
  # - Reticulocyte_percentage
  # - SHBG
  # - Thrombocyte_volume
  # - Total_bilirubin
  # - Triglycerides
  # - Urate
  # - Urea
  # - Vitamin_D
  # - glycated_haemoglobin_hba1c
  # - standing_height
  # - systolic_blood_pressure
